achievements = {
   0: '🦥 "Sloth" (10 correct answers)\n'
      '🐙 "Octopus" (100 correct answers)\n'
      '🐇 "Funny bunny" (500 correct answers)\n'
      '🦄 "Fairy tale unicorn" (1000 correct answers)\n'
      '🐝 "Crazy bee" (3000 correct answers)\n'
      '🦉 "Wise owl" (5000 correct answers)\n'
      ' ‍♂️   "Elf - the keeper of knowledge" (10000 correct answers)',
   1: '🦥 "Sloth" (10 correct answers) - opened ✅\n'
      '🐙 "Octopus" (100 correct answers)\n'
      '🐇 "Funny bunny" (500 correct answers)\n'
      '🦄 "Fairy tale unicorn" (1000 correct answers)\n'
      '🐝 "Crazy bee" (3000 correct answers)\n'
      '🦉 "Wise owl" (5000 correct answers)\n'
      ' ‍♂️   "Elf - the keeper of knowledge" (10000 correct answers)',
   2: '🦥 "Sloth" (10 correct answers) - opened ✅\n'  
      '🐙 "Octopus" (100 correct answers) - opened ✅\n'
      '🐇 "Funny bunny" (500 correct answers)\n'
      '🦄 "Fairy tale unicorn" (1000 correct answers)\n'
      '🐝 "Crazy bee" (3000 correct answers)\n'
      '🦉 "Wise owl" (5000 correct answers)\n'
      ' ‍♂️   "Elf - the keeper of knowledge" (10000 correct answers)',
   3: '🦥 "Sloth" (10 correct answers) - opened ✅\n'
      '🐙 "Octopus" (100 correct answers) - opened ✅\n'
      '🐇 "Funny bunny" (500 correct answers) - opened ✅\n'
      '🦄 "Fairy tale unicorn" (1000 correct answers)\n'
      '🐝 "Crazy bee" (3000 correct answers)\n'
      '🦉 "Wise owl" (5000 correct answers)\n'
      ' ♂️   "Elf - the keeper of knowledge" (10000 correct answers)',
   4: '🦥 "Sloth" (10 correct answers) - opened ✅\n'
      '🐙 "Octopus" (100 correct answers) - opened ✅\n'
      '🐇 "Funny bunny" (500 correct answers) - opened ✅\n'
      '🦄 "Fairy tale unicorn" (1000 correct answers) - opened ✅\n'
      '🐝 "Crazy bee" (3000 correct answers)\n'
      '🦉 "Wise owl" (5000 correct answers)\n'
      ' ‍♂️   "Elf - the keeper of knowledge" (10000 correct answers)',
   5: '🦥 "Sloth" (10 correct answers) - opened ✅\n'
      '🐙 "Octopus" (100 correct answers) - opened ✅\n'
      '🐇 "Funny bunny" (500 correct answers) - opened ✅\n'
      '🦄 "Fairy tale unicorn" (1000 correct answers) - opened ✅\n'
      '🐝 "Crazy bee" (3000 correct answers) - opened ✅\n'
      '🦉 "Wise owl" (5000 correct answers)\n'
      ' ‍♂️   "Elf - the keeper of knowledge" (10000 correct answers)',
   6: '🦥 "Sloth" (10 correct answers) - opened ✅\n'
      '🐙 "Octopus" (100 correct answers) - opened ✅\n'
      '🐇 "Funny bunny" (500 correct answers) - opened ✅\n'
      '🦄 "Fairy tale unicorn" (1000 correct answers) - opened ✅\n'
      '🐝 "Crazy bee" (3000 correct answers) - opened ✅\n'
      '🦉 "Wise owl" (5000 correct answers) - opened ✅\n'
      ' ‍♂️   "Elf - the keeper of knowledge" (10000 correct answers)',
   7: '🦥 "Sloth" (10 correct answers) - opened ✅\n'
      '🐙 "Octopus" (100 correct answers) - opened ✅\n'
      '🐇 "Funny bunny" (500 correct answers) - opened ✅\n'
      '🦄 "Fairy tale unicorn" (1000 correct answers) - opened ✅\n'
      '🐝 "Crazy bee" (3000 correct answers) - opened ✅\n'
      '🦉 "Wise owl" (5000 correct answers) - opened ✅\n'
      ' ‍♂️   "Elf - the keeper of knowledge" (10000 correct answers) - opened ✅\n'
}
